/** Chaînes UI de la boutique (FR par défaut / EN) */
export const SHOP_STRINGS = {
  fr: {
    home: 'Accueil', products: 'Boutique', about: 'À propos', contact: 'Contact',
    terms: 'CGV', searchPlaceholder: 'Rechercher un produit…', search: 'Rechercher',
    cart: 'Panier', addToCart: 'Ajouter au panier', addedToCart: 'Ajouté au panier !',
    viewCart: 'Voir le panier', checkout: 'Commander', category: 'Catégories',
    allCategories: 'Toutes les catégories', sortBy: 'Trier par', filter: 'Filtres',
    price: 'Prix', availability: 'Disponibilité', inStock: 'En stock', outOfStock: 'Rupture',
    featured: 'Produits en vedette', newArrivals: 'Nouveautés', bestSellers: 'Meilleures ventes',
    ourProducts: 'Nos produits', productCount: 'produits', results: 'résultats',
    reviews: 'avis', writeReview: 'Donner mon avis', yourName: 'Votre nom',
    yourReview: 'Votre commentaire', submit: 'Envoyer', rating: 'Note',
    thankReview: 'Merci pour votre avis !', share: 'Partager',
    total: 'Total', subtotal: 'Sous-total', shipping: 'Livraison', free: 'Offerte',
    emptyCart: 'Votre panier est vide', emptyCartCta: 'Découvrir nos produits',
    quantity: 'Quantité', remove: 'Retirer', continueShopping: 'Continuer mes achats',
    contactInfo: 'Vos informations', delivery: 'Livraison', deliveryMethod: 'Mode de livraison',
    payment: 'Paiement', fullName: 'Nom complet', phone: 'Téléphone', city: 'Ville',
    address: 'Adresse', deliveryZone: 'Zone de livraison', pickup: 'Retrait en magasin',
    payNow: 'Payer maintenant', orderNow: 'Confirmer la commande', paymentMethods: 'Moyens de paiement',
    cod: 'Paiement à la livraison', orderSummary: 'Récapitulatif', confirm: 'Confirmer',
    orderConfirmed: 'Commande confirmée', orderTracking: 'Suivi de commande', orderRef: 'Référence',
    status: 'Statut', customer: 'Client', viewAll: 'Tout voir', details: 'Détails',
    newsletter: 'Abonnez-vous à notre newsletter', newsletterSub: 'Recevez nos offres et nouveautés',
    newsletterPlaceholder: 'Votre email', subscribe: 'S\'abonner', subscribed: 'Merci ! Vous êtes abonné.',
    emailSent: 'Un email vous a été envoyé.', promoBanner: 'Livraison offerte à Abidjan dès 50 000 FCFA d\'achat',
    shopNow: 'Je commande', description: 'Description', soldOut: 'Produit épuisé',
    backHome: 'Retour à l\'accueil', messageSent: 'Message envoyé ! Nous vous répondrons rapidement.',
    orderReceived: 'Votre commande a bien été enregistrée.', orderNumber: 'Commande n°',
    trackOrder: 'Suivre ma commande', placeOrder: 'Passer la commande',
    firstName: 'Prénom', lastName: 'Nom', makePayment: 'Procéder au paiement',
    securePayment: 'Paiement sécurisé', payWith: 'Payer avec', phoneForPayment: 'Numéro de téléphone',
    confirmPayment: 'Confirmer le paiement', paySuccess: 'Paiement réussi !', cancel: 'Annuler',
  },
  en: {
    home: 'Home', products: 'Shop', about: 'About', contact: 'Contact',
    terms: 'Terms', searchPlaceholder: 'Search products…', search: 'Search',
    cart: 'Cart', addToCart: 'Add to cart', addedToCart: 'Added to cart!',
    viewCart: 'View cart', checkout: 'Checkout', category: 'Categories',
    allCategories: 'All categories', sortBy: 'Sort by', filter: 'Filters',
    price: 'Price', availability: 'Availability', inStock: 'In stock', outOfStock: 'Out of stock',
    featured: 'Featured products', newArrivals: 'New arrivals', bestSellers: 'Best sellers',
    ourProducts: 'Our products', productCount: 'products', results: 'results',
    reviews: 'reviews', writeReview: 'Write a review', yourName: 'Your name',
    yourReview: 'Your comment', submit: 'Send', rating: 'Rating',
    thankReview: 'Thanks for your review!', share: 'Share',
    total: 'Total', subtotal: 'Subtotal', shipping: 'Shipping', free: 'Free',
    emptyCart: 'Your cart is empty', emptyCartCta: 'Discover our products',
    quantity: 'Quantity', remove: 'Remove', continueShopping: 'Continue shopping',
    contactInfo: 'Your details', delivery: 'Delivery', deliveryMethod: 'Delivery method',
    payment: 'Payment', fullName: 'Full name', phone: 'Phone', city: 'City',
    address: 'Address', deliveryZone: 'Delivery zone', pickup: 'In-store pickup',
    payNow: 'Pay now', orderNow: 'Confirm order', paymentMethods: 'Payment methods',
    cod: 'Cash on delivery', orderSummary: 'Order summary', confirm: 'Confirm',
    orderConfirmed: 'Order confirmed', orderTracking: 'Order tracking', orderRef: 'Reference',
    status: 'Status', customer: 'Customer', viewAll: 'View all', details: 'Details',
    newsletter: 'Subscribe to our newsletter', newsletterSub: 'Get our offers and new products',
    newsletterPlaceholder: 'Your email', subscribe: 'Subscribe', subscribed: 'Thanks! You are subscribed.',
    emailSent: 'An email was sent to you.', promoBanner: 'Free delivery in Abidjan for orders above 50 000 FCFA',
    shopNow: 'Order now', description: 'Description', soldOut: 'Sold out',
    backHome: 'Back to home', messageSent: 'Message sent! We will reply soon.',
    orderReceived: 'Your order has been recorded.', orderNumber: 'Order n°',
    trackOrder: 'Track my order', placeOrder: 'Place order',
    firstName: 'First name', lastName: 'Last name', makePayment: 'Proceed to payment',
    securePayment: 'Secure payment', payWith: 'Pay with', phoneForPayment: 'Phone number',
    confirmPayment: 'Confirm payment', paySuccess: 'Payment successful!', cancel: 'Cancel',
  },
};

export const t = (lang, key) =>
  (SHOP_STRINGS[lang] || SHOP_STRINGS.fr)[key] || SHOP_STRINGS.fr[key] || key;